---
# The Skylight ID for the application.
application: giaNGGMKphdQ

staging:
  authentication: <%= ENV['SUNLIGHT_AUTHENTICATION'] %>

production:
  authentication: <%= ENV['SUNLIGHT_AUTHENTICATION'] %>
