---
# The Skylight ID for the application.
application: <%= ENV['SUNLIGHT_APP_ID'] %>

staging:
  authentication: <%= ENV['SUNLIGHT_AUTHENTICATION'] %>

production:
  authentication: <%= ENV['SUNLIGHT_AUTHENTICATION'] %>
