---
# The Skylight ID for the application.
application: giaNGGMKphdQ

staging:
  authentication: oFRKoNXsAa8ksZVBo-ZdSMJR5npzDm19JMFtehvbRCI

production:
  authentication: AgqMBh-akeXrHjtfK9nYXAKeheJYTXJsayAvx4DOJj0
