---
# The Skylight ID for the application.
application: <%= ENV['SKYLIGHT_APP_ID'] %>

staging:
  authentication: <%= ENV['SKYLIGHT_AUTHENTICATION'] %>

production:
  authentication: <%= ENV['SKYLIGHT_AUTHENTICATION'] %>
